### PR TITLE
Add Chinese Translation

### PR DESCRIPTION
**Pull request by aokeluolai**

### CODE REVIEW

**Comment by Playelectro** [comment]
Thank you so much!

**Comment by aokeluolai** [comment]
> Thank you so much!
You’re welcome

**Comment by SaphieNyako** [comment]
We can only partially use this in the new update cause we changed so much to the quest system. Would you be willing to do another translation when it comes out?

**Comment by SaphieNyako** [comment]
https://github.com/SaphieNyako/Feywild/tree/master/src/main/resources/assets/feywild/lang

Thank you ! :D 
We can only partially use this in the new update cause we changed so much to the quest system. Would you be willing to do another translation when it comes out?

**Comment by aokeluolai** [comment]
> We can only partially use this in the new update cause we changed so much to the quest system. Would you be willing to do another translation when it comes out?

I’d love to. I’ll be in touch with you every time you update

**Comment by aokeluolai** [comment]
> https://github.com/SaphieNyako/Feywild/tree/master/src/main/resources/assets/feywild/lang
> 
> Thank you ! :D
> We can only partially use this in the new update cause we changed so much to the quest system. Would you be willing to do another translation when it comes out?

I’d love to. I’ll keep up with the updates to the module.

**Pull request closed without merging**
