### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by noeppi-noeppi**

### CODE REVIEW

**Comment by noeppi-noeppi** [comment]
Not done with adding `TODO` comments and fixing base stuff yet, just marked this as ready for review so we have less merge conflicts later

**Comment by Playelectro** [comment]
So... should I give the green light for merging now or do you want to add more things?

**Comment by noeppi-noeppi** [comment]
It can be merged. It is not really done yet (not even close) but I want it to be merged as soon as possible because of merge conflicts if any of the files get edited while I create the pull request

**Comment by Playelectro** [comment]
Yeah speaking about that I suggest not touching *for now* the fey entities / mod events / quests since I am working on redoing the whole system

**Comment by Playelectro** [comment]
No, I am currently looking through it and none of the changes you have made to those classes affect what I have done but I still haven't finished reviewing everything

**Comment by Playelectro** [comment]
Oh wait just found the ones in the quest classes... yeah those might need to be reverted since most of the code is gone or changed

**Comment by noeppi-noeppi** [comment]
the changes in the quest system were only chnages that add the missing annotations and reformat the code. I just did this for the whole project. Wehn mergein them, you should be able to just select `Accept Yours` for these files. Then my changes will be discareded. That should not break anything.

**Comment by Playelectro** [comment]
ok

**Pull request merged**
